# Pre-commit configuration for Pipeline Modernization System
repos:
  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]
        exclude: ^src/baml_client/

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]
        exclude: ^src/baml_client/

  # Python linting with ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^src/baml_client/

  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^src/baml_client/
      - id: end-of-file-fixer
        exclude: ^src/baml_client/
      - id: check-yaml
        exclude: ^(baml/|src/baml_client/)
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=2000]
      - id: check-merge-conflict
      - id: debug-statements
        exclude: ^src/baml_client/

  # Documentation checks (simplified to avoid version issues)
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: [--fix, --disable, MD013, MD033, MD041]

# Configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks
  autofix_prs: true
  autoupdate_schedule: monthly
