###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum

from pydantic import BaseModel, ConfigDict

from typing_extensions import TypeAlias, Literal
from typing import Dict, Generic, List, Optional, TypeVar, Union

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class AgentDecision(BaseModel):
    agent_name: Optional[str] = None
    decision: Optional[str] = None
    confidence: Optional[float] = None
    reasoning: Optional[str] = None
    outputs: Optional[str] = None

class AnalysisResults(BaseModel):
    currentPattern: Optional[str] = None
    complexityScore: Optional[float] = None
    performanceImprovement: Optional[str] = None
    costSavings: Optional[str] = None
    awsServices: List[str]
    feasibility: Optional[str] = None

class ArchitectureDecision(BaseModel):
    primary_service: Optional[str] = None
    supporting_services: List[str]
    pattern: Optional[str] = None
    splitter_node: Optional[str] = None
    rationale: Optional[str] = None
    estimated_performance_improvement: Optional[str] = None
    estimated_cost_reduction: Optional[str] = None
    scalability: Optional[str] = None
    splitter_analysis: Optional["SplitterAnalysis"] = None

class BusinessLogic(BaseModel):
    data_sources: List[str]
    transformations: List[str]
    outputs: List[str]
    business_rules: List[str]
    error_handling: Optional["ErrorHandling"] = None
    configuration: List[str]

class ChatContext(BaseModel):
    userMessage: Optional[str] = None
    conversationHistory: List["ChatMessage"]
    currentFileContext: Optional["FileContext"] = None
    workspaceContext: Optional["WorkspaceContext"] = None

class ChatMessage(BaseModel):
    type: Optional[str] = None
    content: Optional[str] = None
    timestamp: Optional[str] = None

class ChatResponse(BaseModel):
    intent: Optional[str] = None
    confidence: Optional[float] = None
    content: Optional[str] = None
    suggestedActions: List[str]
    followUpQuestions: List[str]
    requiresFileAccess: Optional[bool] = None
    recommendedCommands: List[str]

class CodeAnalysisResult(BaseModel):
    packages_detected: List[str]
    trigger_reasons: List[str]
    recommendations: List["CodeRecommendation"]
    lambda_optimizations: List[str]

class CodeRecommendation(BaseModel):
    type: Optional[str] = None
    current_code: Optional[str] = None
    suggested_code: Optional[str] = None
    reason: Optional[str] = None
    confidence_score: Optional[float] = None

class ConflictResolution(BaseModel):
    conflicting_agents: List[str]
    conflict_description: Optional[str] = None
    proposed_solutions: List[str]
    final_decision: Optional[str] = None
    confidence_score: Optional[float] = None

class CostEstimate(BaseModel):
    reduction_percentage: Optional[float] = None
    monthly_savings_usd: Optional[float] = None
    cost_factors: List[str]

class CustomRepoInfo(BaseModel):
    repo_name: Optional[str] = None
    functions_available: List[str]
    classes_available: List[str]
    latest_version: Optional[str] = None
    documentation_url: Optional[str] = None

class DataFlow(BaseModel):
    type: Optional[str] = None
    target: Optional[str] = None
    source: Optional[str] = None
    line_number: Optional[int] = None

class DeprecationAnalysis(BaseModel):
    package_name: Optional[str] = None
    method_name: Optional[str] = None
    is_deprecated: Optional[bool] = None
    deprecation_version: Optional[str] = None
    removal_version: Optional[str] = None
    alternatives: List[str]
    migration_notes: List[str]

class EfficiencyComparison(BaseModel):
    package_name: Optional[str] = None
    alternatives: List["PackageAlternative"]
    recommendation: Optional[str] = None
    performance_notes: List[str]
    lambda_compatibility: Optional[bool] = None

class ErrorHandling(BaseModel):
    has_try_catch: Optional[bool] = None
    exception_types: List[str]
    logging_present: Optional[bool] = None

class FileContext(BaseModel):
    fileName: Optional[str] = None
    language: Optional[str] = None
    content: Optional[str] = None
    analysisResults: Optional["AnalysisResults"] = None

class PackageAlternative(BaseModel):
    name: Optional[str] = None
    performance_score: Optional[float] = None
    lambda_size_mb: Optional[float] = None
    pros: List[str]
    cons: List[str]
    use_cases: List[str]

class PackageInfo(BaseModel):
    name: Optional[str] = None
    version: Optional[str] = None
    description: Optional[str] = None
    docs_url: Optional[str] = None
    repo_url: Optional[str] = None
    is_deprecated: Optional[bool] = None
    deprecated_methods: List[str]
    alternative_packages: List[str]

class PerformanceEstimate(BaseModel):
    improvement_percentage: Optional[float] = None
    bottleneck_reduction: Optional[str] = None
    scalability_factor: Optional[float] = None

class PipelineAnalysis(BaseModel):
    complexity_score: Optional[int] = None
    current_pattern: Optional[str] = None
    modernization_potential: Optional[str] = None
    performance_improvement: Optional[int] = None
    cost_savings: Optional[int] = None
    estimated_effort: Optional[int] = None
    issues: List["PipelineIssue"]
    recommendations: List["PipelineRecommendation"]
    splitting_opportunities: List["SplittingOpportunity"]

class PipelineAnalysisResult(BaseModel):
    current_pattern: Optional[str] = None
    functions_detected: List["PipelineFunction"]
    complexity_score: Optional[float] = None
    migration_feasibility: Optional[str] = None
    estimated_effort_hours: Optional[int] = None
    aws_service_recommendations: List[str]
    business_logic: Optional["BusinessLogic"] = None
    dependencies: List[str]
    data_flow: List["DataFlow"]

class PipelineFunction(BaseModel):
    name: Optional[str] = None
    line_count: Optional[int] = None
    arguments: List[str]
    has_async: Optional[bool] = None
    has_decorators: Optional[bool] = None
    decorators: List[str]
    calls_external_apis: Optional[bool] = None
    file_operations: Optional[bool] = None
    database_operations: Optional[bool] = None
    data_transformations: Optional[bool] = None

class PipelineIssue(BaseModel):
    description: Optional[str] = None
    severity: Optional[str] = None
    line_number: Optional[int] = None

class PipelineRecommendation(BaseModel):
    description: Optional[str] = None
    impact: Optional[str] = None
    effort: Optional[str] = None

class PipelineStageAnalysis(BaseModel):
    stage_name: Optional[str] = None
    complexity: Optional[str] = None
    runtime_estimate: Optional[str] = None
    parallelization_benefit: Optional[str] = None
    bottleneck_potential: Optional[str] = None
    split_justification: Optional[str] = None

class PipelineTransformation(BaseModel):
    modernized_code: Optional[str] = None
    architecture_pattern: Optional[str] = None
    improvements: List[str]
    deployment_notes: List[str]

class Resume(BaseModel):
    name: Optional[str] = None
    email: Optional[str] = None
    experience: List[str]
    skills: List[str]

class SplitterAnalysis(BaseModel):
    optimal_split_point: Optional[str] = None
    split_rationale: Optional[str] = None
    pipeline_stages_analysis: List["PipelineStageAnalysis"]
    performance_impact: Optional["PerformanceEstimate"] = None
    cost_impact: Optional["CostEstimate"] = None

class SplittingOpportunity(BaseModel):
    location: Optional[str] = None
    reason: Optional[str] = None
    benefit: Optional[str] = None

class TransformationRequest(BaseModel):
    pipeline_code: Optional[str] = None
    business_requirements: Optional[str] = None
    target_platform: Optional[str] = None
    performance_goals: Optional[str] = None

class TransformationResult(BaseModel):
    success: Optional[bool] = None
    transformed_code: Optional[str] = None
    validation_results: Optional[str] = None
    infrastructure_code: Optional[str] = None
    git_workflow_results: Optional[str] = None

class ValidationResult(BaseModel):
    functional_equivalence: Optional[bool] = None
    performance_maintained: Optional[bool] = None
    security_validated: Optional[bool] = None
    test_coverage_adequate: Optional[bool] = None
    issues_found: List[str]

class WorkspaceContext(BaseModel):
    pythonFiles: List[str]
    recentAnalyses: List["AnalysisResults"]
    projectType: Optional[str] = None
