###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
from typing import Any, Dict, List, Optional, Type, TypedDict, Union

import baml_py
from typing_extensions import Literal, NotRequired

from . import types
from .type_builder import TypeBuilder
from .types import Check, Checked


class BamlCallOptions(TypedDict, total=False):
    tb: NotRequired[TypeBuilder]
    client_registry: NotRequired[baml_py.baml_py.ClientRegistry]


class HttpRequest:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager


    def AnalyzeChatIntent(
        self,
        message: str,conversationHistory: list[types.ChatMessage],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "AnalyzeChatIntent",
        {
          "message": message,"conversationHistory": conversationHistory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )

    def AnalyzeCodeForTriggers(
        self,
        code: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "AnalyzeCodeForTriggers",
        {
          "code": code,"context": context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )

    def AnalyzePipelineStructure(
        self,
        code: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "AnalyzePipelineStructure",
        {
          "code": code,"context": context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )

    def AnalyzeSplitterOptimization(
        self,
        pipeline_code: str,business_requirements: str,performance_constraints: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "AnalyzeSplitterOptimization",
        {
          "pipeline_code": pipeline_code,"business_requirements": business_requirements,"performance_constraints": performance_constraints,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )

    def CheckDeprecation(
        self,
        package_name: str,method_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "CheckDeprecation",
        {
          "package_name": package_name,"method_name": method_name,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )

    def ComparePackageEfficiency(
        self,
        package_name: str,use_case: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "ComparePackageEfficiency",
        {
          "package_name": package_name,"use_case": use_case,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )

    def CoordinateTransformation(
        self,
        agent_outputs: str,conflicts: str,business_requirements: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "CoordinateTransformation",
        {
          "agent_outputs": agent_outputs,"conflicts": conflicts,"business_requirements": business_requirements,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )

    def ExtractResume(
        self,
        resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "ExtractResume",
        {
          "resume": resume,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )

    def GenerateCodeExplanation(
        self,
        code: str,question: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "GenerateCodeExplanation",
        {
          "code": code,"question": question,"context": context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )

    def GenerateCodeRecommendations(
        self,
        analysis: types.CodeAnalysisResult,package_info: list[types.PackageInfo],efficiency_data: list[types.EfficiencyComparison],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "GenerateCodeRecommendations",
        {
          "analysis": analysis,"package_info": package_info,"efficiency_data": efficiency_data,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )

    def OptimizeArchitecture(
        self,
        pipeline_code: str,business_requirements: str,performance_targets: str,cost_constraints: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "OptimizeArchitecture",
        {
          "pipeline_code": pipeline_code,"business_requirements": business_requirements,"performance_targets": performance_targets,"cost_constraints": cost_constraints,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )

    def ProcessChatMessage(
        self,
        context: types.ChatContext,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "ProcessChatMessage",
        {
          "context": context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )

    def ResolveConflicts(
        self,
        validation_results: str,agent_outputs: str,business_requirements: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "ResolveConflicts",
        {
          "validation_results": validation_results,"agent_outputs": agent_outputs,"business_requirements": business_requirements,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )

    def SuggestNextSteps(
        self,
        currentState: str,userGoals: str,fileContext: Optional[types.FileContext],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "SuggestNextSteps",
        {
          "currentState": currentState,"userGoals": userGoals,"fileContext": fileContext,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )

    def ValidateStrategy(
        self,
        transformation_plan: str,business_requirements: str,risk_tolerance: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "ValidateStrategy",
        {
          "transformation_plan": transformation_plan,"business_requirements": business_requirements,"risk_tolerance": risk_tolerance,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )



class HttpStreamRequest:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager


    def AnalyzeChatIntent(
        self,
        message: str,conversationHistory: list[types.ChatMessage],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "AnalyzeChatIntent",
        {
          "message": message,"conversationHistory": conversationHistory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )

    def AnalyzeCodeForTriggers(
        self,
        code: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "AnalyzeCodeForTriggers",
        {
          "code": code,"context": context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )

    def AnalyzePipelineStructure(
        self,
        code: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "AnalyzePipelineStructure",
        {
          "code": code,"context": context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )

    def AnalyzeSplitterOptimization(
        self,
        pipeline_code: str,business_requirements: str,performance_constraints: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "AnalyzeSplitterOptimization",
        {
          "pipeline_code": pipeline_code,"business_requirements": business_requirements,"performance_constraints": performance_constraints,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )

    def CheckDeprecation(
        self,
        package_name: str,method_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "CheckDeprecation",
        {
          "package_name": package_name,"method_name": method_name,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )

    def ComparePackageEfficiency(
        self,
        package_name: str,use_case: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "ComparePackageEfficiency",
        {
          "package_name": package_name,"use_case": use_case,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )

    def CoordinateTransformation(
        self,
        agent_outputs: str,conflicts: str,business_requirements: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "CoordinateTransformation",
        {
          "agent_outputs": agent_outputs,"conflicts": conflicts,"business_requirements": business_requirements,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )

    def ExtractResume(
        self,
        resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "ExtractResume",
        {
          "resume": resume,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )

    def GenerateCodeExplanation(
        self,
        code: str,question: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "GenerateCodeExplanation",
        {
          "code": code,"question": question,"context": context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )

    def GenerateCodeRecommendations(
        self,
        analysis: types.CodeAnalysisResult,package_info: list[types.PackageInfo],efficiency_data: list[types.EfficiencyComparison],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "GenerateCodeRecommendations",
        {
          "analysis": analysis,"package_info": package_info,"efficiency_data": efficiency_data,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )

    def OptimizeArchitecture(
        self,
        pipeline_code: str,business_requirements: str,performance_targets: str,cost_constraints: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "OptimizeArchitecture",
        {
          "pipeline_code": pipeline_code,"business_requirements": business_requirements,"performance_targets": performance_targets,"cost_constraints": cost_constraints,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )

    def ProcessChatMessage(
        self,
        context: types.ChatContext,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "ProcessChatMessage",
        {
          "context": context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )

    def ResolveConflicts(
        self,
        validation_results: str,agent_outputs: str,business_requirements: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "ResolveConflicts",
        {
          "validation_results": validation_results,"agent_outputs": agent_outputs,"business_requirements": business_requirements,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )

    def SuggestNextSteps(
        self,
        currentState: str,userGoals: str,fileContext: Optional[types.FileContext],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "SuggestNextSteps",
        {
          "currentState": currentState,"userGoals": userGoals,"fileContext": fileContext,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )

    def ValidateStrategy(
        self,
        transformation_plan: str,business_requirements: str,risk_tolerance: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "ValidateStrategy",
        {
          "transformation_plan": transformation_plan,"business_requirements": business_requirements,"risk_tolerance": risk_tolerance,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )



__all__ = ["HttpRequest", "HttpStreamRequest"]
